require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/shared_login_data", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SharedLoginDatum. As you add validations to SharedLoginDatum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SharedLoginDatum.create! valid_attributes
      get shared_login_data_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      shared_login_datum = SharedLoginDatum.create! valid_attributes
      get shared_login_datum_url(shared_login_datum)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_shared_login_datum_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      shared_login_datum = SharedLoginDatum.create! valid_attributes
      get edit_shared_login_datum_url(shared_login_datum)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SharedLoginDatum" do
        expect {
          post shared_login_data_url, params: { shared_login_datum: valid_attributes }
        }.to change(SharedLoginDatum, :count).by(1)
      end

      it "redirects to the created shared_login_datum" do
        post shared_login_data_url, params: { shared_login_datum: valid_attributes }
        expect(response).to redirect_to(shared_login_datum_url(SharedLoginDatum.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SharedLoginDatum" do
        expect {
          post shared_login_data_url, params: { shared_login_datum: invalid_attributes }
        }.to change(SharedLoginDatum, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post shared_login_data_url, params: { shared_login_datum: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shared_login_datum" do
        shared_login_datum = SharedLoginDatum.create! valid_attributes
        patch shared_login_datum_url(shared_login_datum), params: { shared_login_datum: new_attributes }
        shared_login_datum.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the shared_login_datum" do
        shared_login_datum = SharedLoginDatum.create! valid_attributes
        patch shared_login_datum_url(shared_login_datum), params: { shared_login_datum: new_attributes }
        shared_login_datum.reload
        expect(response).to redirect_to(shared_login_datum_url(shared_login_datum))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        shared_login_datum = SharedLoginDatum.create! valid_attributes
        patch shared_login_datum_url(shared_login_datum), params: { shared_login_datum: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested shared_login_datum" do
      shared_login_datum = SharedLoginDatum.create! valid_attributes
      expect {
        delete shared_login_datum_url(shared_login_datum)
      }.to change(SharedLoginDatum, :count).by(-1)
    end

    it "redirects to the shared_login_data list" do
      shared_login_datum = SharedLoginDatum.create! valid_attributes
      delete shared_login_datum_url(shared_login_datum)
      expect(response).to redirect_to(shared_login_data_url)
    end
  end
end
